"""Save generated outlines as markdown files for human review."""

import os
import re
from datetime import datetime

REVIEW_DIR = os.path.join(os.path.dirname(__file__))


def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text[:60]


def save_outline(outline_data: dict) -> str:
    """Write one outline to a markdown file (one file per keyword group). Returns the file path."""
    rag_result = outline_data["rag_result"]
    group = rag_result["group"]
    classification = rag_result["classification"]
    related = rag_result["related_articles"]
    sources = group["sources"]
    outline_text = outline_data["outline"]

    date_str = datetime.now().strftime("%Y-%m-%d")
    slug = slugify(group["keyword"])
    filename = f"{date_str}_{slug}.md"
    filepath = os.path.join(REVIEW_DIR, filename)

    platforms = sorted(set(s["platform"] for s in sources))

    sources_md = "\n".join(
        f"- [{s['platform']}] [{s['title']}]({s['url']})" for s in sources
    )

    related_md = ""
    if related:
        lines = "\n".join(
            f"- [{a['title']}]({a['url']}) — similarity `{a['similarity']}`"
            for a in related
        )
        related_md = f"\n## Related Existing Articles\n{lines}\n"

    content = f"""---
date: {date_str}
keyword: {group['keyword']}
platforms: {', '.join(platforms)}
source_count: {len(sources)}
classification: {classification}
status: pending_review
---

# Outline: {group['keyword']}

> **{len(sources)} real signals found** across: {', '.join(platforms)}
> **Classification:** `{classification}` (similarity score: {rag_result['top_similarity']})

## Trend Sources
{sources_md}
{related_md}
---

{outline_text}

---
*Generated by content-engine — review and approve before publishing.*
"""

    with open(filepath, "w") as f:
        f.write(content)

    return filepath


def save_all_outlines(outlines: list[dict]) -> list[str]:
    paths = []
    for o in outlines:
        path = save_outline(o)
        print(f"[review] Saved → {path}")
        paths.append(path)
    return paths
